# Generated by Django 4.2.5 on 2023-09-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='viewed_by',
        ),
    ]
