# Generated by Django 4.2.5 on 2023-09-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='connections',
        ),
    ]
